name: adapto_scaffold
description: A drop-in replacement for Scaffold with adaptive layouts (mobile, tablet, desktop).
version: 0.0.1
homepage: https://github.com/Dev-Arnab-Flutter/adaptive_scaffold
repository: https://github.com/Dev-Arnab-Flutter/adaptive_scaffold

environment:
  sdk: ">=2.18.0 <4.0.0"
license: "MIT"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
